In [4]:
from IPython.utils import path

from data_manager.storage.csv_backend import CSVStorage

In [5]:
import pandas as pd
import numpy as np

In [6]:

np.random.seed(42)

data = {
    'Numeric_Col': np.random.randint(1, 100, 20).astype(float),
    'String_Col': np.random.choice(['Alpha', 'Beta', 'Gamma', 'Delta', 'Alpha'], 20),
    'Mixed_Col': np.random.choice(['A', 1, 'B', 2, None], 20)
}

myData = pd.DataFrame(data=data)

In [7]:
myData.head()

   Numeric_Col String_Col Mixed_Col
0         52.0      Delta         B
1         93.0      Alpha      None
2         15.0      Alpha         A
3         72.0      Delta         1
4         61.0       Beta         2

In [8]:
dataManager = CSVStorage()

In [9]:
dataManager.store(data=myData)

In [10]:
dataManager.data.head()

   Numeric_Col String_Col Mixed_Col
0         52.0      Delta         B
1         93.0      Alpha      None
2         15.0      Alpha         A
3         72.0      Delta         1
4         61.0       Beta         2

In [11]:
print(id(dataManager.data) == id(myData))

True

In [1]:
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data.csv"

In [13]:
myData.to_csv(test_data_path, index=False)

In [ ]:
dataManager_1 = CSVStorage()
dataManager_1.load(test_data_path)

In [ ]:
dataManager_1.data

In [2]:
from data_manager.storage.csv_backend import CSVStorage

In [3]:
myData = CSVStorage()
myData.load(test_data_path)

In [4]:
myData.savepoint("SP1")

In [5]:
myData.data

    Numeric_Col String_Col Mixed_Col
0          52.0      Delta         B
1          93.0      Alpha       NaN
2          15.0      Alpha         A
3          72.0      Delta         1
4          61.0       Beta         2
5          21.0      Alpha         A
6          83.0      Delta         2
7          87.0      Alpha         1
8          75.0      Alpha         1
9          75.0      Gamma         A
10         88.0      Gamma         1
11         24.0       Beta       NaN
12          3.0      Delta         1
13         22.0      Delta         2
14         53.0      Gamma         2
15          2.0      Delta         2
16         88.0      Delta         2
17         30.0      Alpha       NaN
18         38.0      Gamma         B
19          2.0      Alpha         A

In [6]:
from data_manager.jobs.data_engineer import DataEngineer
enginner = DataEngineer(myData)

In [7]:
enginner.removeNull()

2026-06-16 00:35:03,245 - INFO - executing removeNull....
2026-06-16 00:35:03,247 - INFO - 3 null rows dropped

In [8]:
myData.stack

deque([<data_manager.transactions.savepoint.Savepoint at 0x21d7a236990>])

In [9]:
myData.stack[-1].deltas.items()

dict_items([('__table__',     Numeric_Col String_Col Mixed_Col
0          52.0      Delta         B
1          93.0      Alpha       NaN
2          15.0      Alpha         A
3          72.0      Delta         1
4          61.0       Beta         2
5          21.0      Alpha         A
6          83.0      Delta         2
7          87.0      Alpha         1
8          75.0      Alpha         1
9          75.0      Gamma         A
10         88.0      Gamma         1
11         24.0       Beta       NaN
12          3.0      Delta         1
13         22.0      Delta         2
14         53.0      Gamma         2
15          2.0      Delta         2
16         88.0      Delta         2
17         30.0      Alpha       NaN
18         38.0      Gamma         B
19          2.0      Alpha         A)])

In [10]:
myData.data

    Numeric_Col String_Col Mixed_Col
0          52.0      Delta         B
2          15.0      Alpha         A
3          72.0      Delta         1
4          61.0       Beta         2
5          21.0      Alpha         A
6          83.0      Delta         2
7          87.0      Alpha         1
8          75.0      Alpha         1
9          75.0      Gamma         A
10         88.0      Gamma         1
12          3.0      Delta         1
13         22.0      Delta         2
14         53.0      Gamma         2
15          2.0      Delta         2
16         88.0      Delta         2
18         38.0      Gamma         B
19          2.0      Alpha         A

In [11]:
myData.roleback()

In [12]:
myData.data

    Numeric_Col String_Col Mixed_Col
0          52.0      Delta         B
1          93.0      Alpha       NaN
2          15.0      Alpha         A
3          72.0      Delta         1
4          61.0       Beta         2
5          21.0      Alpha         A
6          83.0      Delta         2
7          87.0      Alpha         1
8          75.0      Alpha         1
9          75.0      Gamma         A
10         88.0      Gamma         1
11         24.0       Beta       NaN
12          3.0      Delta         1
13         22.0      Delta         2
14         53.0      Gamma         2
15          2.0      Delta         2
16         88.0      Delta         2
17         30.0      Alpha       NaN
18         38.0      Gamma         B
19          2.0      Alpha         A