In [4]:
from IPython.utils import path

from data_manager.storage.csv_backend import CSVStorage

In [5]:
import pandas as pd
import numpy as np

In [6]:

np.random.seed(42)

data = {
    'Numeric_Col': np.random.randint(1, 100, 20).astype(float),
    'String_Col': np.random.choice(['Alpha', 'Beta', 'Gamma', 'Delta', 'Alpha'], 20),
    'Mixed_Col': np.random.choice(['A', 1, 'B', 2, None], 20)
}

myData = pd.DataFrame(data=data)

In [7]:
myData.head()

   Numeric_Col String_Col Mixed_Col
0         52.0      Delta         B
1         93.0      Alpha      None
2         15.0      Alpha         A
3         72.0      Delta         1
4         61.0       Beta         2

In [8]:
dataManager = CSVStorage()

In [9]:
dataManager.store(data=myData)

In [10]:
dataManager.dd.head()

   Numeric_Col String_Col Mixed_Col
0         52.0      Delta         B
1         93.0      Alpha      None
2         15.0      Alpha         A
3         72.0      Delta         1
4         61.0       Beta         2

In [11]:
print(id(dataManager.dd) == id(myData))

True

In [12]:
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data.csv"

In [13]:
myData.to_csv(test_data_path, index=False)

In [ ]:
dataManager_1 = CSVStorage()
dataManager_1.read(test_data_path)

In [ ]:
dataManager_1.dd