In [1]:
import pdb

from pandas._libs.tslibs.offsets import Nano

from tabular.jobs import data_engineer
from tabular.storage.csv_backend import CSVStorage
from tabular.jobs.data_engineer import DataEngineer

In [2]:
# import pandas as pd
# import numpy as np
#
# np.random.seed(42)
#
# # Create base dataframe
# df = pd.DataFrame({
#     "id": np.arange(1, 51),
#     "name": np.random.choice(
#         ["Alice", "Bob", "Charlie", "David", "Eva", None],
#         50
#     ),
#     "age": np.random.choice(
#         [22, 25, 28, 31, 35, np.nan],
#         50
#     ),
#     "salary": np.random.choice(
#         [45000, 55000, 65000, 75000, np.nan],
#         50
#     ),
#     "department": np.random.choice(
#         ["HR", "IT", "Finance", "Sales", None],
#         50
#     ),
#     "city": np.random.choice(
#         ["Delhi", "Mumbai", "Pune", "Bangalore", None],
#         50
#     ),
#     "rating": np.random.choice(
#         [1, 2, 3, 4, 5, np.nan],
#         50
#     ),
#     "experience": np.random.choice(
#         [1, 3, 5, 7, 10, np.nan],
#         50
#     ),
#     "status": np.random.choice(
#         ["Active", "Inactive", None],
#         50
#     ),
#     "score": np.random.choice(
#         [55.5, 67.8, 72.1, 88.4, 91.2, np.nan],
#         50
#     )
# })
#
# # Introduce duplicate rows
# df.iloc[10] = df.iloc[0]
# df.iloc[20] = df.iloc[5]
# df.iloc[30] = df.iloc[10]
#
# print(df)
#
# print("\nShape:", df.shape)
# print("\nDuplicate Rows:")
# print(df[df.duplicated()])
#
# print("\nNull Values Count:")
# print(df.isnull().sum())

In [3]:
# df.to_csv("D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv")

In [4]:
data_manager = CSVStorage()
test_data_path = "D:\\workspace\\Dev tools\\PythonProjects\\DataManager\\tests\\Data\\test_data_1.csv"
data_manager.read(test_data_path)

In [10]:
data_manager.dd

,Unnamed: 0,id,name,age,salary,department,city,rating,experience,status,score
7,7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
11,11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
18,18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
26,26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
47,47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8

In [6]:
data_engineer_job = DataEngineer(data_manager)

In [7]:
data_engineer_tasks = [
    {
        "function": "removeDublicate",
        "params": {}
    },
    {
        "function": "removeNull",
        "params": {
            "method" : "drop"
        }
    }
]

In [8]:
data_engineer_job.run(data_engineer_tasks)

In [9]:
data_manager.dd

,Unnamed: 0,id,name,age,salary,department,city,rating,experience,status,score
7,7,8,Charlie,31.0,65000.0,HR,Mumbai,5.0,10.0,Inactive,88.4
11,11,12,Charlie,35.0,45000.0,Sales,Bangalore,3.0,5.0,Inactive,72.1
18,18,19,Bob,25.0,45000.0,HR,Pune,3.0,10.0,Active,88.4
26,26,27,David,25.0,65000.0,Finance,Bangalore,1.0,7.0,Inactive,88.4
47,47,48,David,35.0,65000.0,HR,Mumbai,1.0,1.0,Active,67.8