In [1]:
from data_manager.jobs.data_engineer import DataEngineer
from data_manager.jobs.data_analytics import DataAnalytics
from data_manager.storage.json_backend import JSONStorage
from data_manager.runner import Runner

In [2]:
test_data_path = "../Data/test_data_2.json"

In [3]:
mystorage = JSONStorage()

In [4]:
mystorage.load(test_data_path)

In [5]:
mystorage.data.head()

,id,name,age,salary,department,city,experience,rating,active,email
0,1,Alice,25.0,50000.0,IT,Delhi,2.0,4.5,True,alice@example.com
1,2,Bob,NaN,60000.0,HR,Mumbai,4.0,4.2,True,bob@example.com
2,3,Charlie,30.0,NaN,Finance,Bangalore,6.0,NaN,False,charlie@example.com
3,4,NaN,28.0,55000.0,IT,NaN,3.0,4.1,True,david@example.com
4,5,Eva,22.0,45000.0,Marketing,Pune,NaN,3.9,True,NaN

In [6]:
mystorage.savepoint("SP1")

In [15]:
dataengineercontext = [
    {
        "task":"removeDuplicates",
        "function":"removeDuplicates",
        "params":{}
    },
    {
        "task":"removeNull",
        "function":"removeNull",
        "params":{
            "method":"const",
            "num_const":0,
            "category_const":"Unknown"
        }
    }
]

dataanalyticscontext = [
    {
        "task":"Summary_of_the_data",
        "function":"summary",
        "params":{}
    },
    {
        "task":"Data_profile",
        "function":"profile",
        "params":{}
    }
]

In [16]:
works = [
    {
        "job":DataEngineer(mystorage),
        "contexts":dataengineercontext
    },
    {
        "job":DataAnalytics(mystorage),
        "contexts":dataanalyticscontext
    }
]

In [17]:
pipeline = Runner(works)

In [18]:
pipeline.run()

2026-06-16 14:35:28,734 - INFO - executing removeDuplicates....
2026-06-16 14:35:28,737 - INFO - 0 duplicate rows removed
2026-06-16 14:35:28,739 - INFO - executing removeNull....
2026-06-16 14:35:28,743 - INFO - 0 null values are filled
2026-06-16 14:35:28,745 - INFO - executing summary....
2026-06-16 14:35:28,748 - INFO - executing profile....
2026-06-16 14:35:28,749 - INFO - executing missing_analysis....
2026-06-16 14:35:28,751 - INFO - executing duplicate_analysis....
2026-06-16 14:35:28,754 - INFO - executing summary....

In [19]:
mystorage.data.head()

,id,name,age,salary,department,city,experience,rating,active,email
0,1,Alice,25.0,50000.0,IT,Delhi,2.0,4.5,True,alice@example.com
1,2,Bob,0.0,60000.0,HR,Mumbai,4.0,4.2,True,bob@example.com
2,3,Charlie,30.0,0.0,Finance,Bangalore,6.0,0.0,False,charlie@example.com
3,4,Unknown,28.0,55000.0,IT,Unknown,3.0,4.1,True,david@example.com
4,5,Eva,22.0,45000.0,Marketing,Pune,0.0,3.9,True,Unknown

In [20]:
mystorage.roleback()

In [21]:
mystorage.data.head()

,id,name,age,salary,department,city,experience,rating,active,email
0,1,Alice,25.0,50000.0,IT,Delhi,2.0,4.5,True,alice@example.com
1,2,Bob,NaN,60000.0,HR,Mumbai,4.0,4.2,True,bob@example.com
2,3,Charlie,30.0,NaN,Finance,Bangalore,6.0,NaN,False,charlie@example.com
3,4,NaN,28.0,55000.0,IT,NaN,3.0,4.1,True,david@example.com
4,5,Eva,22.0,45000.0,Marketing,Pune,NaN,3.9,True,NaN

In [22]:
works[1]["job"].results["Summary_of_the_data"]

{'Rows': 9,
 'Columns': 10,
 'Data type': id              int64
 name              str
 age           float64
 salary        float64
 department        str
 city              str
 experience    float64
 rating        float64
 active           bool
 email             str
 dtype: object,
 'Memory usage(Bytes)': np.int64(2497),
 'Missing values': {'id': 0,
  'name': 0,
  'age': 0,
  'salary': 0,
  'department': 0,
  'city': 0,
  'experience': 0,
  'rating': 0,
  'active': 0,
  'email': 0}}